Simplified uptime check
SUNET/puppet-sunet pull request #225
Opened 2024-12-05 13:50 UTC by richir-sunet

A simplified uptime check script, with slightly different output. Old one also had a bug and was very hard to read.

2024-12-06 08:01 UTC, mickenordin reviewed
A suggestion about overriding the default values

2024-12-06 08:01 UTC, mickenordin commented on manifests/nagios.pp
> +    command_line => '/usr/lib/nagios/plugins/check_uptime.py'
and here it would be:
```
command_line => "/usr/lib/nagios/plugins/check_uptime.py -w ${uptimew} -c ${uptimec}"
```

2024-12-06 08:04 UTC, richir-sunet commented on manifests/nagios/nrpe_check_uptime.pp
Sounds like a good idea.

2024-12-10 13:35 UTC, mickenordin requested changes
Two bug on line 95 in manifests/nagios.pp

You need double quotes around the command and a dollar sign is missing on {uptime}

2024-12-10 13:48 UTC, mickenordin approved these changes
Looking good!

2024-12-10 13:49 UTC, merged